description: Fork by Brian Zelip for combining all docs into one page.

markdown: kramdown
highlighter: pygments
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: noifniof3nioaniof3nioafafinoafnoif

repository: https://github.com/brianzelip/jekyll
help_url: https://github.com/jekyll/jekyll-help

collections:
  docs:
    output: true
